--BAI 1--
--TAO BANG--
CREATE TABLE BTHTTT1.XE
(
    MAXE VARCHAR2(3) CONSTRAINT PK_XE PRIMARY KEY,
    BIENKS VARCHAR2(9),
    MATUYEN VARCHAR2(4),
    SOGHET1 NUMBER,
    SOGHET2 NUMBER
);

CREATE TABLE BTHTTT1.TUYEN
(
    MATUYEN VARCHAR2(4) CONSTRAINT PK_TUYEN PRIMARY KEY,
    BENDAU VARCHAR2(3),
    BENCUOI VARCHAR2(3),
    GIATUYEN NUMBER,
    NGXB DATE,
    TGDK NUMBER
)

CREATE TABLE BTHTTT1.KHACH
(
    MAHK VARCHAR2(4) CONSTRAINT PK_KHACH PRIMARY KEY,
    HOTEN VARCHAR2(20),
    GIOITINH VARCHAR2(3),
    CMND VARCHAR2(9)
)

CREATE TABLE BTHTTT1.VEXE
(
    MATUYEN VARCHAR2(4),
    MAHK VARCHAR2(4),
    NGMUA DATE,
    GIAVE NUMBER,
    PRIMARY KEY(MATUYEN,MAHK)
)

ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';

ALTER USER BTHTTT1 QUOTA UNLIMITED ON USERS;

--NHAP DU LIEU--
INSERT INTO BTHTTT1.XE VALUES('X01', '52LD-4393', 'T11A', 20, 20);
INSERT INTO BTHTTT1.XE VALUES('X02', '59LD-7247', 'T32D', 36, 36);
INSERT INTO BTHTTT1.XE VALUES('X03', '55LD-6850', 'T06F', 15, 15);

INSERT INTO BTHTTT1.TUYEN VALUES('T11A', 'SG', 'DL', 210.000, '26/12/2016', 6);
INSERT INTO BTHTTT1.TUYEN VALUES('T32D', 'PT', 'SG', 120.000, '30/12/2016', 4);
INSERT INTO BTHTTT1.TUYEN VALUES('T06F', 'NT', 'DNG', 225.000, '02/01/2017', 7);

--HANHKHACH--
INSERT INTO BTHTTT1.KHACH VALUES ('KH01', 'Lam Van Ben', 'Nam', 655615896);
INSERT INTO BTHTTT1.KHACH VALUES ('KH02', 'Duon Thi Luc', 'Nu', 275648642);
INSERT INTO BTHTTT1.KHACH VALUES ('KH03', 'Hoang Thanh Tung', 'Nam', 456889143);

INSERT INTO BTHTTT1.VEXE VALUES ('T11A', 'KH01', '20/12/2016', 210.000);
INSERT INTO BTHTTT1.VEXE VALUES ('T32D', 'KH02', '25/12/2016', 144.000);
INSERT INTO BTHTTT1.VEXE VALUES ('T06F', 'KH03', '30/12/2016', 270.000);

/*DROP TABLE BTHTTT1.XE
DROP TABLE BTHTTT1.TUYEN
DROP TABLE BTHTTT1.KHACH
DROP TABLE BTHTTT1.VEXE*/

--THEM KHOA NGOAI--

ALTER TABLE BTHTTT1.XE
ADD CONSTRAINT FK_XE_TUYEN_MATUYEN FOREIGN KEY(MATUYEN) REFERENCES BTHTTT1.TUYEN(MATUYEN)

ALTER TABLE BTHTTT1.VEXE
ADD CONSTRAINT FK_VEXE_TUYEN_MATUYEN FOREIGN KEY(MATUYEN) REFERENCES BTHTTT1.TUYEN(MATUYEN)

ALTER TABLE BTHTTT1.VEXE
ADD CONSTRAINT FK_VEXE_KHACH_MAHK FOREIGN KEY(MAHK) REFERENCES BTHTTT1.KHACH(MAHK)

--CAU 3--
SELECT BTHTTT1.TUYEN.MATUYEN FROM BTHTTT1.TUYEN
WHERE BTHTTT1.TUYEN.TGDK > 5 AND BTHTTT1.TUYEN.GIATUYEN > 200.000

--CAU 4 TRIGGER--


--CAU 5--
SELECT * FROM BTHTTT1.VEXE
WHERE EXTRACT(MONTH FROM (NGMUA)) = 12
ORDER BY GIAVE DESC

--CAU 6--
SELECT DISTINCT MATUYEN
FROM BTHTTT1.VEXE 
WHERE EXTRACT(YEAR FROM NGMUA) = 2016
GROUP BY MATUYEN
HAVING COUNT(MATUYEN) <= ALL (
                                SELECT COUNT(MATUYEN)
                                FROM BaiTapCNTT1.VEXE
                                WHERE EXTRACT(YEAR FROM NGMUA) = 2016
                                GROUP BY MATUYEN
                             );

--CAU 7--
SELECT VEXE.MATUYEN
FROM BTHTTT1.VEXE VEXE JOIN BaiTapCNTT1.HANHKHACH HK ON VEXE.MAHK = HK.MAHK
WHERE GIOITINH = 'Nam'                  
INTERSECT                  
SELECT BTHTTT1.MATUYEN
FROM BaiTapCNTT1.VEXE VEXE JOIN BaiTapCNTT1.HANHKHACH HK ON VEXE.MAHK = HK.MAHK
WHERE GIOITINH = 'Nu';

--CAU 8--
SELECT *
FROM BTHTTT1.HANHKHACH HK
WHERE GIOITINH = 'Nu'
      AND NOT EXISTS (
                        SELECT *
                        FROM BTHTTT1.TUYEN TUYEN 
                        WHERE NOT EXISTS (
                                            SELECT *
                                            FROM BTHTTT1.VEXE VEXE
                                            WHERE VEXE.MATUYEN = TUYEN.MATUYEN
                                                  AND VEXE.MAHK = HK.MAHK
                                         )
                     );