/*1.Tạo bảng HANGHANGKHONG*/
CREATE TABLE BaitapKHDL3.HANGHANGKHONG
(
    MAHANG VARCHAR2(2) CONSTRAINT PK_HHK PRIMARY KEY,
    TENHANG VARCHAR2(50),
    NGTL DATE,
    DUONGBAY NUMBER
)

/*Tạo bảng CHUYENBAY*/
CREATE TABLE BaitapKHDL3.CHUYENBAY 
(
    MACB VARCHAR2(5) CONSTRAINT PK_CB PRIMARY KEY,
    MAHANG VARCHAR2(2),
    XUATPHAT NVARCHAR2(50),
    DIEMDEN NVARCHAR2(50),
    BATDAU DATE,
    TGBAY NUMBER
)

/*Tạo bảng NHANVIEN*/
CREATE TABLE BaitapKHDL3.NHANVIEN
(
    MANV VARCHAR2(4) CONSTRAINT PK_NV PRIMARY KEY,
    HOTEN NVARCHAR2(20),
    GIOITINH NVARCHAR2(4),
    NGSINH DATE,
    NGVL DATE,
    CHUYENMON NVARCHAR2(50)
)

/*. Tạo bảng PHANCONG */
CREATE TABLE BaitapKHDL3.PHANCONG
(
    MACB VARCHAR2(5),
    MANV VARCHAR2(4),
    NHIEMVU NVARCHAR2(50),
    CONSTRAINT PK_PC PRIMARY KEY(MACB,MANV)
)
/*2. Nhập dữ liệu cho 4 table*/
ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';
ALTER USER BaitapKHDL3 QUOTA UNLIMITED ON USERS;

INSERT INTO BaitapKHDL3.HANGHANGKHONG VALUES('VN', 'Vietnam Airlines', '15/01/1956', 52);
INSERT INTO BaitapKHDL3.HANGHANGKHONG VALUES('VJ', 'Vietjet Air', '25/12/2011', 33);
INSERT INTO BaitapKHDL3.HANGHANGKHONG VALUES('BL', 'Jetstar Pacific Airlines', '01/12/1990', 13);

INSERT INTO BaitapKHDL3.CHUYENBAY VALUES('VN550', 'VN', N'TP.HCM', N'Singapore', '20/12/2015 13:15', 2);
INSERT INTO BaitapKHDL3.CHUYENBAY VALUES('VJ331', 'VJ', N'Đà Nẵng', N'Vinh', '28/12/2015 22:30', 1);
INSERT INTO BaitapKHDL3.CHUYENBAY VALUES('BL696', 'BL', N'TP.HCM', N'Đà Lạt', '24/12/2015 06:00', 0.5);

INSERT INTO BaitapKHDL3.NHANVIEN VALUES('NV01', N'Lâm Văn Bền', N'Nam', '10/09/1978', '05/06/2000', N'Phi công');
INSERT INTO BaitapKHDL3.NHANVIEN VALUES('NV02', N'Dương Thị Lục', N'Nữ', '22/03/1989', '12/11/2013', N'Tiếp viên');
INSERT INTO BaitapKHDL3.NHANVIEN VALUES('NV03', N'Hoàng Thanh Tùng', N'Nam', '29/07/1983', '11/04/2007', N'Tiếp viên');

INSERT INTO BaitapKHDL3.PHANCONG VALUES('VN550', 'NV01', N'Cơ trưởng');
INSERT INTO BaitapKHDL3.PHANCONG VALUES('VN550', 'NV02', N'Tiếp viên');
INSERT INTO BaitapKHDL3.PHANCONG VALUES('BL696', 'NV03', N'Tiếp viên trưởng');

/*Tạo ràng buộc khóa ngoại*/
ALTER  TABLE BaitapKHDL3.CHUYENBAY ADD CONSTRAINT FK_CB_HHK FOREIGN KEY (MAHANG) REFERENCES BaitapKHDL3.HANGHANGKHONG(MAHANG);
ALTER  TABLE BaitapKHDL3.PHANCONG ADD CONSTRAINT FK_PC_CB FOREIGN KEY (MACB) REFERENCES BaitapKHDL3.CHUYENBAY(MACB);
ALTER  TABLE BaitapKHDL3.PHANCONG ADD CONSTRAINT FK_PC_NV FOREIGN KEY (MANV) REFERENCES BaitapKHDL3.NHANVIEN(MANV);

/*3. Hiện thực ràng buộc toàn vẹn sau: Chuyên môn của nhân viên chỉ được nhận giá trị là ‘Phi công’ hoặc ‘Tiếp viên’.*/
ALTER TABLE BaitapKHDL3.NHANVIEN
ADD CONSTRAINT CHK_CHUYENMON
  CHECK (CHUYENMON IN (N'Phi công', N'Tiếp viên'));
  

/*4. Hiện thực ràng buộc toàn vẹn sau: Ngày bắt đầu chuyến bay luôn lớn hơn ngày thành lập hãng hàng không quản lý chuyến bay đó.*/

/*5. Tìm tất cả các nhân viên có sinh nhậttrong tháng 07.*/
SELECT *
FROM BaitapKHDL3.NHANVIEN
WHERE EXTRACT (MONTH FROM NGSINH) = 7

/*6. Tìm chuyến bay có số nhân viên nhiều nhất..*/
SELECT MACB
FROM BaitapKHDL3.PHANCONG
GROUP BY MACB
HAVING COUNT(MANV)=(
	SELECT MAX(SL)
	FROM(
		SELECT COUNT(MANV) AS SL
		FROM BaitapKHDL3.PHANCONG
		GROUP BY MACB
    )
)
   
/*7. Với mỗi hãng hàng không, thống kê số chuyến bay có điểm xuất phát là ‘Đà Nẵng’ và có số nhân viên được phân công ít hơn 2..*/ 
SELECT H.MAHANG, COUNT(CB.MACB) AS SOLUONG
FROM BaitapKHDL3.HANGHANGKHONG H LEFT JOIN (   
    SELECT C.MACB, MAHANG
    FROM BaitapKHDL3.CHUYENBAY C LEFT JOIN BaitapKHDL3.PHANCONG P ON C.MACB = P.MACB
    WHERE XUATPHAT = N'Đà Nẵng'
    GROUP BY C.MACB, MAHANG
    HAVING COUNT(MANV) < 2
    ) CB ON H.MAHANG = CB.MAHANG
GROUP BY H.MAHANG

/*8.Tìm nhân viên được phân công tham gia tất cả các chuyến bay.*/
SELECT MANV
FROM BaitapKHDL3.NHANVIEN NV
WHERE NOT EXISTS(
    SELECT *
    FROM  BaitapKHDL3.CHUYENBAY CB
    WHERE NOT EXISTS(
        SELECT * 
        FROM BaitapKHDL3.PHANCONG PC
        WHERE NV.MANV = PC.MANV AND PC.MACB= CB.MACB
    )
)