/* 1.Tao bảng xe*/
CREATE TABLE BaitapKHDL1.XE
(
    MAXE VARCHAR2(3) CONSTRAINT PK_XE PRIMARY KEY,
    BIENKS VARCHAR2(10),
    MATUYEN VARCHAR2(4),
    SOGHET1 NUMBER,
    SOGHET2 NUMBER
)
/*2.Tạo bảng TUYEN*/
CREATE TABLE BaitapKHDL1.TUYEN
(
    MATUYEN VARCHAR2(4) CONSTRAINT PK_TUYEN PRIMARY KEY,
    BENDAU VARCHAR(3) NOT NULL,
    BENCUOI VARCHAR(3) NOT NULL,
    GIATUYEN DECIMAL,
    NGXB DATE,
    TGDK NUMBER
)
/*3.Tạo bảng KHACHHANG*/
CREATE TABLE BaitapKHDL1.KHACHHANG
(
    MAKH VARCHAR(4) CONSTRAINT PK_KHACHHANG PRIMARY KEY,
    HOTEN VARCHAR(20),
    GIOITINH VARCHAR(3),
    CMND NUMBER(11)
)
/*4. Tạo bảng VEXE*/
CREATE TABLE BaitapKHDL1.VEXE
(
    MATUYEN VARCHAR(4),
    MAKH VARCHAR(4),
    NGMUA DATE,
    GIAVE DECIMAL,
    CONSTRAINT PK_VEXE PRIMARY KEY(MATUYEN,MAKH,NGMUA)
)

ALTER SESSION SET NLS_DATE_FORMAT = ' DD/MM/YYYY HH24:MI:SS ' ;
ALTER USER BaitapKHDL1 QUOTA UNLIMITED ON USERS;
/*5.INSERT dữ liệu*/
INSERT INTO BaitapKHDL1.XE VALUES('X01', '52LD-4393', 'T11A', 20, 20);
INSERT INTO BaitapKHDL1.XE VALUES('X02', '59LD-7247', 'T32D', 36, 36);
INSERT INTO BaitapKHDL1.XE VALUES('X03', '55LD-6850', 'T06F', 15, 15);

INSERT INTO BaitapKHDL1.TUYEN VALUES('T11A', 'SG', 'DL', 210.000, '26/12/2016', 6);
INSERT INTO BaitapKHDL1.TUYEN VALUES('T32D', 'PT', 'SG', 120.000, '30/12/2016', 4);
INSERT INTO BaitapKHDL1.TUYEN VALUES('T06F', 'NT', 'DNG', 225.000, '02/01/2017', 7);

INSERT INTO BaitapKHDL1.KHACHHANG VALUES ('KH01', 'Lâm Văn Bền', 'Nam', 655615896);
INSERT INTO BaitapKHDL1.KHACHHANG VALUES ('KH02', 'Dương Thị Lục', 'Nu', 275648642);
INSERT INTO BaitapKHDL1.KHACHHANG VALUES ('KH03', 'Hoàng Thanh Tùng', 'Nam', 456889143);

INSERT INTO BaitapKHDL1.VEXE VALUES ('T11A', 'KH01', '20/12/2016', 210.000);
INSERT INTO BaitapKHDL1.VEXE VALUES ('T32D', 'KH02', '25/12/2016', 144.000);
INSERT INTO BaitapKHDL1.VEXE VALUES ('T06F', 'KH03', '30/12/2016', 270.000);

/*6.Tìm tất cả các vé xe mua trong tháng 12, sắp xếp kết quả giảm dần theo giá vé*/

SELECT *
FROM BaitapKHDL1.VEXE
WHERE EXTRACT(MONTH FROM(NGMUA)) = 12
ORDER  BY GIAVE DESC;

/*7.Tìm tuyến xe có số vé xe ít nhất trong năm 2016*/
SELECT MATUYEN
FROM BaitapKHDL1.VEXE
WHERE EXTRACT(YEAR FROM NGMUA)=2016
GROUP BY MATUYEN
HAVING COUNT (MATUYEN) <= ALL
                    (
                    SELECT COUNT(MATUYEN)FROM BaitapKHDL1.VEXE
                    WHERE EXTRACT(YEAR FROM NGMUA)=2016
                    GROUP BY MATUYEN
                    );

/*8.Tìm tuyến xe có cả hành khách nam và hành khách nữ mua vé.*/
SELECT BaitapKHDL1.TUYEN.MATUYEN 
FROM BaitapKHDL1.TUYEN, BaitapKHDL1.KHACHHANG,BaitapKHDL1.VEXE
WHERE VEXE.MAKH = KHACHHANG.MAKH AND VEXE.MATUYEN = TUYEN.MATUYEN 
AND GIOITINH='Nam'
INTERSECT
SELECT BaitapKHDL1.TUYEN.MATUYEN 
FROM BaitapKHDL1.TUYEN, BaitapKHDL1.KHACHHANG,BaitapKHDL1.VEXE
WHERE VEXE.MAKH = KHACHHANG.MAKH AND VEXE.MATUYEN = TUYEN.MATUYEN 
AND GIOITINH='Nu'

/*9.Tìm hành khách nữ đã từng mua vé tất cả các tuyến xe.*/
SELECT BaitapKHDL1.KHACHHANG.MAKH, BaitapKHDL1.KHACHHANG.HOTEN,BaitapKHDL1.KHACHHANG.CMND
FROM BaitapKHDL1.KHACHHANG
WHERE GIOITINH = 'Nu' AND NOT EXISTS (
                                    SELECT *
                                    FROM BaitapKHDL1.TUYEN
                                    WHERE NOT EXISTS(
                                    SELECT*
                                    FROM BaitapKHDL1.VEXE
                                    WHERE TUYEN.MATUYEN = VEXE.MATUYEN 
                                    AND KHACHHANG.MAKH=VEXE.MAKH))