CREATE TABLE BaitapKHDL1.USER_NEW
(
    U_ID VARCHAR2(3) CONSTRAINT PK_USER PRIMARY KEY,
    USERNAME VARCHAR2(50),
    PASS VARCHAR2(50),
    REGDAY DATE,
    NATIONALITY NVARCHAR2(50)
)

/*Tạo bảng CHANNEL*/
CREATE TABLE BaitapKHDL1.CHANNEL
(
    CHANNELID VARCHAR2(4) CONSTRAINT PK_CHANNEL PRIMARY KEY,
    CNAME NVARCHAR2(50),
    SUBSCRIBES NUMBER,
    OWNNER VARCHAR2(3),
    CREATED DATE
);
/*Tạo bảng VIDEO*/
CREATE TABLE BaitapKHDL1.VIDEO
(
    VIDEOID VARCHAR2(7) CONSTRAINT PK_VIDEO PRIMARY KEY,
    TITLE NVARCHAR2(50),
    DURATION NUMBER,
    AGE NUMBER
);
/*Tạo bảng SHARES*/
CREATE TABLE BaitapKHDL1.SHARES
(
    VIDEOID VARCHAR2(7),
    CHANNELID VARCHAR2(4),
    CONSTRAINT PK_SHARE PRIMARY KEY(VIDEOID, CHANNELID)
);

ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';
ALTER USER BaitapKHDL1 QUOTA UNLIMITED ON USERS;
/*Nhập liệu bảng cho các bảng*/
INSERT INTO BaitapKHDL1.USER_NEW VALUES ('001', 'faptv', '123456abc', '01/01/2014', N'Việt Nam');
INSERT INTO BaitapKHDL1.USER_NEW VALUES ('002', 'kemxoitv', '@147869iii', '05/06/2015', N'Campuchia');
INSERT INTO BaitapKHDL1.USER_NEW VALUES ('003', 'openshare', 'qwertyuiop', '12/05/2009', N'Việt Nam');

INSERT INTO BaitapKHDL1.CHANNEL VALUES ('C120', N'FAP TV', 2343, '001', '02/01/2014');
INSERT INTO BaitapKHDL1.CHANNEL VALUES ('C905', N'Kem xôi TV', 1032, '002', '09/07/2015');
INSERT INTO BaitapKHDL1.CHANNEL VALUES ('C357', N'OpenShare Cáfe', 5064, '003', '10/12/2010');

INSERT INTO BaitapKHDL1.VIDEO VALUES ('V100229', N'FAPtv Cơm Nguội Tập 41 - Đột Nhập', 469, 18);
INSERT INTO BaitapKHDL1.VIDEO VALUES ('V211002', N'Kem xôi: Tập 31 - Mẩy Kool tình yêu của anh', 312, 16);
INSERT INTO BaitapKHDL1.VIDEO VALUES ('V400002', N'Nơi tình yêu kết thúc - Hoàng Tuấn', 378, 0);

INSERT INTO BaitapKHDL1.SHARES VALUES ('V100229', 'C905');
INSERT INTO BaitapKHDL1.SHARES VALUES ('V211002', 'C120');
INSERT INTO BaitapKHDL1.SHARES VALUES ('V400002', 'C357');

/*Tạo khóa ngoại*/
ALTER TABLE BaitapKHDL1.CHANNEL ADD FOREIGN KEY (OWNNER) REFERENCES BaitapKHDL1.USER_NEW(U_ID);
ALTER TABLE BaitapKHDL1.SHARES ADD CONSTRAINT FK_SHARE_VIDEO FOREIGN KEY (VIDEOID) REFERENCES BaitapKHDL1.VIDEO(VIDEOID);
ALTER TABLE BaitapKHDL1.SHARES ADD CONSTRAINT FK_SHARE_CHANNEL FOREIGN KEY (CHANNELID) REFERENCES BaitapKHDL1.CHANNEL(CHANNELID);

/*3. Hiện thực ràng buộc toàn vẹn sau: Ngày đăng ký đượcmặc định là ngày hiện tại.*/
CREATE OR REPLACE TRIGGER TRG_USER
BEFORE INSERT ON BaitapKHDL1.USER_NEW
FOR EACH ROW
BEGIN
    :NEW.REGDAY := SYSDATE;
END;

/*5. Tìm tất cả các video có giới hạn độ tuổi từ 16 trở lên.*/
SELECT *
FROM BaitapKHDL1.VIDEO
WHERE AGE >= 16;

/*6. Tìm kênh có số người theo dõi nhiều nhất*/
SELECT *
FROM BaitapKHDL1.CHANNEL
WHERE SUBSCRIBES = (
    SELECT MAX(SUBSCRIBES)
    FROM BaitapKHDL1.CHANNEL
);

/*7. Với mỗi video có giới hạn độ tuổi là 18, thống kê số kênh đã chia sẻ*/
SELECT BaitapKHDL1.VIDEO.VIDEOID, COUNT(CHANNELID) AS SOLUONG
FROM BaitapKHDL1.VIDEO INNER JOIN BaitapKHDL1.SHARES ON VIDEO.VIDEOID = SHARES.VIDEOID
WHERE AGE >=18
GROUP BY BaitapKHDL1.VIDEO.VIDEOID;

/*8. Tìm video được tất cả các kênh chia sẻ*/
SELECT * 
FROM BaitapKHDL1.VIDEO V
WHERE NOT EXISTS(
    SELECT *
    FROM  BaitapKHDL1.CHANNEL C
    WHERE NOT EXISTS(
        SELECT * 
        FROM BaitapKHDL1.SHARES S
        WHERE V.VIDEOID = S.VIDEOID 
        AND C.CHANNELID = S.CHANNELID
    )
)