--1. Tạo user tên là BAITHI gồm có 4 table XE, TUYEN, KHACH, VEXE. Tạo khóa chính, khóa ngoại cho các table đó.--
--Tạo bảng XE--
CREATE TABLE BTCNTT1.XE
(
    MAXE VARCHAR2(3) CONSTRAINT PK_XE PRIMARY KEY,
    BIENKS VARCHAR2(9),
    MATUYEN VARCHAR(4),
    SOGHET1 NUMBER,
    SOGHET2 NUMBER
)

--Tạo bảng TUYEN--
CREATE TABLE BTCNTT1.TUYEN
(
    MATUYEN VARCHAR(4) CONSTRAINT PK_TUYEN PRIMARY KEY,
    BENDAU VARCHAR(3),
    BENCUOI VARCHAR(3),
    GIATUYEN DECIMAL,
    NGXB DATE,
    TGDK NUMBER
)

--Tạo bảng KHACH--
CREATE TABLE BTCNTT1.KHACH
(
    MAHK VARCHAR(4) CONSTRAINT PK_KHACHHANG PRIMARY KEY,
    HOTEN NVARCHAR2(20),
    GIOITINH NVARCHAR2(4),
    CMND NUMBER(11)
)

--Tạo bảng VEXE--
CREATE TABLE BTCNTT1.VEXE
(
    MATUYEN VARCHAR(4),
    MAHK VARCHAR(4),
    NGMUA DATE,
    GIAVE DECIMAL,
    CONSTRAINT PK_VEXE PRIMARY KEY(MATUYEN,MAHK,NGMUA)
)

ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';
ALTER USER BTCNTT1 QUOTA UNLIMITED ON USERS;
/*2.1. Nhập liệu cho table XE*/
INSERT INTO BTCNTT1.XE VALUES('X01', '52LD-4393', 'T11A', 20, 20);
INSERT INTO BTCNTT1.XE VALUES('X02', '59LD-7247', 'T32D', 36, 36);
INSERT INTO BTCNTT1.XE VALUES('X03', '55LD-6850', 'T06F', 15, 15);
/*2.2. Nhập liệu cho table TUYEN*/
INSERT INTO BTCNTT1.TUYEN VALUES('T11A', 'SG', 'DL', '210000', '26/12/2016', 6);
INSERT INTO BTCNTT1.TUYEN VALUES('T32D', 'PT', 'SG', '120000', '30/12/2016', 4);
INSERT INTO BTCNTT1.TUYEN VALUES('T06F', 'NT', 'DNG', '225000', '02/01/2017', 7);
/*2.3. Nhập liệu cho table KHACH*/
INSERT INTO BTCNTT1.KHACH VALUES('KH01', N'Lâm Văn Bền', N'Nam', 655615896);
INSERT INTO BTCNTT1.KHACH VALUES('KH02', N'Dương Thị Lục', N'Nữ', 275648642);
INSERT INTO BTCNTT1.KHACH VALUES('KH03', N'Hoàng Thanh Tùng', N'Nam', 456889143);
/*2.4. Nhập liệu cho table VEXE*/
INSERT INTO BTCNTT1.VEXE VALUES('T11A', 'KH01', '20/12/2016', 210000);
INSERT INTO BTCNTT1.VEXE VALUES('T32D', 'KH02', '25/12/2016', 144000);
INSERT INTO BTCNTT1.VEXE VALUES('T06F', 'KH03', '30/12/2016', 270000);

ALTER  TABLE BTCNTT1.XE ADD CONSTRAINT FK_XE_TUYEN FOREIGN KEY (MATUYEN) REFERENCES BTCNTT1.TUYEN(MATUYEN);
ALTER  TABLE BTCNTT1.VEXE ADD CONSTRAINT FK_VEXE_TUYEN FOREIGN KEY (MATUYEN) REFERENCES BTCNTT1.TUYEN(MATUYEN);
ALTER  TABLE BTCNTT1.VEXE ADD CONSTRAINT FK_VEXE_KHACH FOREIGN KEY (MAHK) REFERENCES BTCNTT1.KHACH(MAHK);

--3. Hiện thực ràng buộc toàn vẹn sau: Các tuyến xe có Thời gian dự kiến lớn hơn 5 tiếng luôn có giá tuyến lớn hơn 200.000.--
ALTER TABLE BTCNTT1.TUYEN
ADD CONSTRAINT CHK_GIATUYEN
  CHECK ((TGDK >5 AND GIATUYEN >200000) OR TGDK<=5)
ENABLE NOVALIDATE;

---5. Tìm tất cả các vé xe mua trong tháng 12, sắp xếp kết quả giảm dần theo giá vé.---
SELECT *
FROM BTCNTT1.VEXE
WHERE EXTRACT (MONTH FROM NGMUA) = 12
ORDER BY GIAVE DESC

---6. Tìm tuyến xe có số vé xe ít nhất trong năm 2016.---
SELECT TUYEN.MATUYEN
FROM BTCNTT1.TUYEN LEFT JOIN BTCNTT1.VEXE ON TUYEN.MATUYEN = VEXE.MATUYEN
WHERE EXTRACT(YEAR FROM NGMUA) = 2016
GROUP BY TUYEN.MATUYEN
HAVING COUNT(TUYEN.MATUYEN)<=(
	SELECT MIN(SL)
	FROM(
		SELECT COUNT(MATUYEN) AS SL
		FROM BTCNTT1.VEXE
		WHERE EXTRACT(YEAR FROM NGMUA) = 2016
		GROUP BY MATUYEN
    )
)
   
---7. Tìm tuyến xe có cả hành khách nam và hành khách nữ mua vé.--- 
SELECT MATUYEN
FROM BTCNTT1.VEXE INNER JOIN BTCNTT1.KHACH ON VEXE.MAHK = KHACH.MAHK
WHERE  GIOITINH = N'Nam'
INTERSECT
SELECT MATUYEN
FROM BTCNTT1.VEXE INNER JOIN BTCNTT1.KHACH ON VEXE.MAHK = KHACH.MAHK
WHERE GIOITINH = N'Nữ'

---8.Tìm hành khách nữ đã từng mua vé tất cả các tuyến xe.---
SELECT * 
FROM BTCNTT1.KHACH
WHERE GIOITINH = N'Nữ' AND NOT EXISTS(
    SELECT *
    FROM  BTCNTT1.TUYEN
    WHERE NOT EXISTS(
        SELECT * 
        FROM BaiTapCNTT1.VEXE
        WHERE VEXE.MAHK = KHACH.MAHK AND VEXE.MATUYEN = TUYEN.MATUYEN
    )
)
