-- Nhóm 4 - 18521414 - Trần Quốc Thành
/*----- CÂU 1. Tạo user tên BAITHI gồm có 4 table HANGHANGKHONG, CHUYENBAY, NHANVIEN,
PHANCONG. Tạo khóa chính, khóa ngoại cho các table đó.  -----*/

-- Tạo user
ALTER SESSION SET "_ORACLE_SCRIPT" = true;

CREATE USER BTH2 IDENTIFIED BY "12345";

GRANT sysdba TO BTH2;

-- 1. Tạo bảng HANGHANGKHONG
CREATE TABLE BTH2.HANGHANGKHONG
(
	MAHANG VARCHAR(2) CONSTRAINT PK_HANGHANGKHONG PRIMARY KEY,
	TENHANG VARCHAR(50),
	NGTL DATE,
	DUONGBAY NUMBER
);

-- 2. Tạo bảng CHUYENBAY
CREATE TABLE BTH2.CHUYENBAY 
(
	MACB VARCHAR(5) CONSTRAINT PK_CHUYENBAY PRIMARY KEY,
	MAHANG VARCHAR(2),
	XUATPHAT VARCHAR(20),
	DIEMDEN VARCHAR(20),
	BATDAU DATE,
	TGBAY DECIMAL(18, 1)
);

-- 3. Tạo bảng NHANVIEN
CREATE TABLE BTH2.NHANVIEN
(
	MANV VARCHAR(4) CONSTRAINT PK_NHANVIEN PRIMARY KEY,
	HOTEN VARCHAR(50),
	GIOITINH VARCHAR(5),
	NGSINH DATE,
	NGVL DATE,
	CHUYENMON VARCHAR(20)
);

-- 4. Tạo bảng PHANCONG
CREATE TABLE BTH2.PHANCONG
(
	MACB VARCHAR(5),
	MANV VARCHAR(4),
	NHIEMVU VARCHAR(30),
	CONSTRAINT PK_PHANCONG PRIMARY KEY (MACB,MANV)
);

/*----- CÂU 2. Nhập dữ liệu cho 4 table như đề bài. -----*/
ALTER SESSION SET NLS_DATE_FORMAT = ' DD/MM/YY HH24:MI:SS ';

ALTER USER BTH2 QUOTA UNLIMITED ON USERS;

-- 1. Nhập liệu bảng HANGHANGKHONG
INSERT INTO BTH2.HANGHANGKHONG VALUES ('VN', 'Vietnam Airlines', '15/01/1956', 52);
INSERT INTO BTH2.HANGHANGKHONG VALUES ('VJ', 'Vietjet Air', '25/12/2011', 33);
INSERT INTO BTH2.HANGHANGKHONG VALUES ('BL', 'Jetstar Pacific Airlines', '01/12/1990', 13);

-- 2. Nhập liệu bảng CHUYENBAY
INSERT INTO BTH2.CHUYENBAY VALUES ('VN550', 'VN', 'TP.HCM', N'Singapore', '20/12/2015 13:15', 2);
INSERT INTO BTH2.CHUYENBAY VALUES ('VJ331', 'VJ', 'Đà Nẵng', N'Vinh', '28/12/2015 22:30', 1);
INSERT INTO BTH2.CHUYENBAY VALUES ('BL696', 'BL', 'TP.HCM', N'Đà Lạt', '24/12/2015 06:00', 0.5);

-- 3. Nhập liệu bảng NHANVIEN
INSERT INTO BTH2.NHANVIEN VALUES	('NV01', N'Lâm Văn Bền', N'Nam', '10/09/1978', '05/06/2000', N'Phi công');
INSERT INTO BTH2.NHANVIEN VALUES ('NV02', N'Dương Thị Lục', N'Nữ', '22/03/1989', '12/11/2013', N'Tiếp viên');
INSERT INTO BTH2.NHANVIEN VALUES ('NV03', N'Hoàng Thanh Tùng', N'Nam', '29/07/1983', '11/04/2007', N'Tiếp viên');

-- 4. Nhập liệu bảng PHANCONG
INSERT INTO BTH2.PHANCONG VALUES ('VN550', 'NV01', N'Cơ trưởng');
INSERT INTO BTH2.PHANCONG VALUES ('VN550', 'NV02', N'Tiếp viên');
INSERT INTO BTH2.PHANCONG VALUES ('BL696', 'NV03', N'Tiếp viên trưởng');

-- Thêm khóa ngoại
ALTER TABLE BTH2.CHUYENBAY ADD FOREIGN KEY (MAHANG) REFERENCES BTH2.HANGHANGKHONG(MAHANG);
ALTER TABLE BTH2.PHANCONG ADD FOREIGN KEY (MACB) REFERENCES BTH2.CHUYENBAY(MACB);
ALTER TABLE BTH2.PHANCONG ADD FOREIGN KEY (MANV) REFERENCES BTH2.NHANVIEN(MANV);

-- Kiểm tra
SELECT * FROM BTH2.HANGHANGKHONG;
SELECT * FROM BTH2.CHUYENBAY;
SELECT * FROM BTH2.NHANVIEN;
SELECT * FROM BTH2.PHANCONG;

/*----- CÂU 4. Hiện thực ràng buộc toàn vẹn sau: Ngày bắt đầu chuyến bay luôn 
lớn hơn ngày thành lập hãng hàng không quản lý chuyến bay đó.  -----*/
/*
- Bối cảnh: HANGHANGKHONG, CHUYENBAY

- Nội dung: Với mọi hhk thuộc HANGHANGKHONG, tồn tại cb thuộc CHUYENBAY: 
                hhk.MAHANG = cb.MAHANG và cb.BATDAU > hhk.NGTL 
                
- Bảng tầm ảnh hường:
                Thêm    Xóa     Sửa
HANGHANGKHONG    -       -       +(NGTL)
CHUYENBAY        +       -       +(BATDAU, MAHANG)
*/

-- Trigger UPDATE trên bảng HANHANGKHONG
CREATE OR REPLACE TRIGGER UPDATE_HHK
AFTER UPDATE
ON BTH2.HANGHANGKHONG FOR EACH ROW
DECLARE
    v_batdau DATE;
BEGIN
    SELECT BATDAU INTO v_batdau
    FROM BTH2.CHUYENBAY CB
    WHERE CB.MAHANG = :NEW.MAHANG;
    
    IF (v_batdau <= :NEW.NGTL) THEN
        RAISE_APPLICATION_ERROR(-20100, 'Ngày bắt đầu chuyến bay luôn 
            lớn hơn ngày thành lập hãng hàng không quản lý chuyến bay đó');
    END IF;    
END;

-- Kiểm tra DL đang có
SELECT HHK.MAHANG, NGTL, BATDAU
FROM BTH2.HANGHANGKHONG HHK JOIN BTH2.CHUYENBAY CB ON HHK.MAHANG = CB.MAHANG;

-- TH lỗi: VN: NGTL = 15/01/1956, BATDAU = '13h15 20/12/2015' 
--          -> Sửa NGTL = 20/12/2016
UPDATE BTH2.HANGHANGKHONG
SET NGTL = '20/12/2016'
WHERE MAHANG = 'VN';

-- TH Thành công: VN: NGTL = 15/01/1956, BATDAU = '13h15 20/12/2015' 
--          -> Sửa NGTL = 20/12/2000
UPDATE BTH2.HANGHANGKHONG
SET NGTL = '20/12/2000'
WHERE MAHANG = 'VN';

-------------------------------------------------------------------------------
-- Trigger INSERT, UPDATE trên bảng CHUYENBAY
CREATE OR REPLACE TRIGGER INSERT_UPDATE_CB
AFTER INSERT OR UPDATE
ON BTH2.CHUYENBAY FOR EACH ROW
DECLARE
    v_ngtl DATE;
BEGIN
    SELECT NGTL INTO v_ngtl
    FROM BTH2.HANGHANGKHONG HHK
    WHERE HHK.MAHANG = :NEW.MAHANG;
    
    IF (:NEW.BATDAU <= v_ngtl) THEN
        RAISE_APPLICATION_ERROR(-20100, 'Ngày bắt đầu chuyến bay luôn 
            lớn hơn ngày thành lập hãng hàng không quản lý chuyến bay đó');
    END IF;    
END;

-- Kiểm tra DL đang có
SELECT HHK.MAHANG, NGTL, BATDAU
FROM BTH2.HANGHANGKHONG HHK JOIN BTH2.CHUYENBAY CB ON HHK.MAHANG = CB.MAHANG;

-- TH UPDATE
-- TH lỗi: VN: NGTL = 15/01/1956, BATDAU = 13h15 20/12/2015 
--          -> Sửa BATDAU = 13h15 20/12/1900
UPDATE BTH2.CHUYENBAY
SET BATDAU = '20/12/1900 13:15'
WHERE MAHANG = 'VN';

-- TH Thành công: VN: NGTL = 15/01/1956, BATDAU = '13h15 20/12/2015' 
--          -> Sửa BATDAU = 13h15 20/12/2000
UPDATE BTH2.CHUYENBAY
SET BATDAU = '20/12/2000 13:15'
WHERE MAHANG = 'VN';


-- TH INSERT
-- TH lỗi: VN: NGTL = 15/01/1956
--          -> Thêm CB có BATDAU = 13h15 20/12/1900
INSERT INTO BTH2.CHUYENBAY VALUES ('VN300', 'VN', 'TP.HCM', N'Bình Định', '20/12/1900 13:15', 1);


-- TH Thành công: VN: NGTL = 15/01/1956 
--          -> Thêm CB có BATDAU = 13h15 20/12/2000
INSERT INTO BTH2.CHUYENBAY VALUES ('VN300', 'VN', 'TP.HCM', N'Bình Định', '20/12/2000 13:15', 1);

-- Kiểm tra lại DL vừa thêm
SELECT *
FROM BTH2.CHUYENBAY CB 
WHERE CB.MACB = 'VN300';

-------------------------------------------------------------------------------
-- Trả DL lại trạng thái ban đầu khi chưa kiểm tra Trigger
DELETE FROM BTH2.CHUYENBAY
WHERE MACB = 'VN300';

UPDATE BTH2.CHUYENBAY
SET BATDAU = '20/12/2015 13:15'
WHERE MAHANG = 'VN';

UPDATE BTH2.HANGHANGKHONG
SET NGTL = '15/01/1956'
WHERE MAHANG = 'VN';



